# @package task
defaults:
  - /task/hdmi-base
  - _self_

name: G1TrackSuitcase

objects:
  object:
    _target_: box
    name: object
    size: [0.2, 0.3, 0.4]
    mass: 2.0
    rgba: [0.4, 0.3, 0.2, 1.0]

command:
  object_name: object
  object_root_body_name: object
  object_tracking_body_names: [object]
  object_tracking_joint_names: []
