# @package task
defaults:
  - tracking-base
  - object: ???
  - _self_

name: G1TrackHDMI
project: hdmi

objects:
  object:
    _target_: ???

command:
  _target_: hdmi.RobotObjectTracking
  future_steps: [-4, -2, 0, 1, 2, 3, 8, 16]
  object_name: object
  object_root_body_name: ???
  object_tracking_body_names: ???
  object_tracking_joint_names: []

observation:
  policy:
    object_pose_local:
      _target_: hdmi.object_pose_local
  command:
    object_spatial_error_local:
      _target_: mimic_lite.body_spatial_error_local
      body_names: ${task.command.object_tracking_body_names}
  command_short:
    ref_root_pos_future_local:
      future_steps: ${task.command.future_steps}
    ref_root_ori_future_b:
      future_steps: ${task.command.future_steps}
    ref_joint_pos_future:
      future_steps: ${task.command.future_steps}
reward:
  object_tracking:
    body_pos:
      _target_: mimic_lite.body_pos_local_exp
      body_names: ${task.command.object_tracking_body_names}
      weight: 1.0
      sigma: 0.5
    body_ori:
      _target_: mimic_lite.body_ori_local_exp
      body_names: ${task.command.object_tracking_body_names}
      weight: 1.0
      sigma: 0.5

termination:
  object_pos_error:
    _target_: cum_body_pos_error
    body_names: ${task.command.object_tracking_body_names}
    min_steps: 5
    threshold: 0.5
  object_ori_error:
    _target_: cum_body_ori_error
    body_names: ${task.command.object_tracking_body_names}
    min_steps: 5
    threshold: 0.8
