# @package task

defaults:
  - hdmi-base
  - variant: root-aware-global
  - _self_
  - patches: v1_1
  - override object: omomo-rigid5
  - override motion: g1/omomo-rigid5
  - override observation/command: root_joint

name: G1TrackHDMIOmomoRigid5PCDOnly
command:
  motion_palm_frames: true

observation:
  object_pcd:
    surface_points:
      _target_: hdmi.object_surface_points_local
  object_category:
    category:
      _target_: hdmi.object_category
  object_motion_progress:
    progress:
      _target_: hdmi.object_motion_progress
