# @package task

reward:
  tracking:
    root_pos:
      _target_: mimic_lite.body_pos_exp
  object_tracking:
    body_pos:
      _target_: mimic_lite.body_pos_local_exp
    body_ori:
      _target_: mimic_lite.body_ori_local_exp

termination:
  root_pos_error:
    is_timeout: false
