# @package task

robot:
  name: hdmi_robot_from_motion
  dataset_root: ${task.command.motion_cfgs.suitcase.path}
  mode: 15

objects:
  object:
    _target_: hdmi_object_mesh_variants
    motion_cfgs: ${task.command.motion_cfgs}
    seed: ${seed}

command:
  object_name: object
  object_root_body_name: object
  object_tracking_body_names: [object]
  object_tracking_joint_names: []

observation:
  object_pcd:
    surface_points:
      _target_: hdmi.object_surface_points_local
  object_category:
    category:
      _target_: hdmi.object_category
  object_motion_progress:
    progress:
      _target_: hdmi.object_motion_progress
