# @package task

robot:
  name: hdmi_robot_from_motion
  dataset_root: ${task.objects.object.dataset_root}
  mode: 15

objects:
  object:
    _target_: hdmi_object_asset
    dataset_root: ../any4hdmi/output/g1/omomo_suitcase_gmr_accepted

command:
  object_name: object
  object_root_body_name: object
  object_tracking_body_names: [object]
  object_tracking_joint_names: []

observation:
  policy:
    object_pose_local:
      _target_: hdmi.object_pose_local
